# Generated by Django 6.1 on 2026-08-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='无标题', max_length=200, verbose_name='文章标题'),
            preserve_default=False,
        ),
    ]
