# Generated by Django 6.1 on 2026-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='字数统计'),
        ),
    ]
