# Generated by Django 6.1 on 2026-09-03 07:17

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_enable_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '笔记', 'verbose_name_plural': '笔记列表'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '主题', 'verbose_name_plural': '主题列表'},
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='entry_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='entry_text_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='topic_text_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['tree_id', 'lft'], name='learning_logs_topic_tree_i79ab'),
        ),
    ]
